language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get install libgnome2-dev libgoocanvas-dev libcurl4-openssl-dev libsoup2.4-dev libgtk2.0-dev libgnomevfs2-dev
script: autoreconf -fi && ./configure && make
