language: c
sudo: false
compiler:
  - gcc
  - clang
env:
  global:
    - CMAKE_VERSION=3.8.1
addons:
  apt:
    packages:
    - libgoocanvas-dev
    - libcurl4-openssl-dev
    - libsoup2.4-dev
    - libgtk2.0-dev
    - libgnomevfs2-dev
script:
  # install a working version from upstream, the Ubuntu version is too old
  - wget -O /tmp/cmake.tar --no-check-certificate https://cmake.org/files/v$(echo ${CMAKE_VERSION} | sed 's/\.[0-9]*$//')/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz
  - tar xf /tmp/cmake.tar -C /tmp
  - export PATH=/tmp/cmake-${CMAKE_VERSION}-Linux-x86_64/bin:${PATH}
  - mkdir build
  - pushd build
  - cmake -D ENABLE_TESTS=On .. && make VERBOSE=1 && make test
  - cmake -D SERVER_EDITABLE=On -D PICKER_MENU=On . && make VERBOSE=1 && make test
