language: c
sudo: false
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libgoocanvas-dev
    - libcurl4-openssl-dev
    - libsoup2.4-dev
    - libgtk2.0-dev
    - libgnomevfs2-dev
script:
  - mkdir build
  - autoreconf -fi && cd build && ../configure && make
